// This file is auto-generated by @hey-api/openapi-ts

export const AdminGamePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        itch_url: {
            type: 'string',
            title: 'Itch Url'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        status: {
            '$ref': '#/components/schemas/GameStatus'
        },
        featured_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Featured At'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'itch_url', 'status'],
    title: 'AdminGamePublic'
} as const;

export const AdminGamesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/AdminGamePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'AdminGamesPublic'
} as const;

export const DuplicateCheckResultSchema = {
    properties: {
        url_exists: {
            type: 'boolean',
            title: 'Url Exists',
            default: false
        },
        existing_game_slug: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Existing Game Slug'
        },
        similar_titles: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Similar Titles',
            default: []
        }
    },
    type: 'object',
    title: 'DuplicateCheckResult'
} as const;

export const GameCreateSchema = {
    properties: {
        url: {
            type: 'string',
            maxLength: 2048,
            minLength: 1,
            title: 'Url'
        }
    },
    type: 'object',
    required: ['url'],
    title: 'GameCreate'
} as const;

export const GameLinkPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        url: {
            type: 'string',
            title: 'Url'
        },
        platform: {
            '$ref': '#/components/schemas/LinkPlatform',
            default: 'itch'
        },
        is_primary: {
            type: 'boolean',
            title: 'Is Primary',
            default: true
        },
        normalized_url: {
            type: 'string',
            title: 'Normalized Url'
        }
    },
    type: 'object',
    required: ['id', 'url', 'normalized_url'],
    title: 'GameLinkPublic'
} as const;

export const GamePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        cover_image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cover Image Url'
        },
        status: {
            '$ref': '#/components/schemas/GameStatus'
        },
        submitter_id: {
            type: 'string',
            format: 'uuid',
            title: 'Submitter Id'
        },
        submitter_itch_username: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Submitter Itch Username'
        },
        reviewed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reviewed At'
        },
        rejection_reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rejection Reason'
        },
        duplicate_title_warning: {
            type: 'boolean',
            title: 'Duplicate Title Warning',
            default: false
        },
        kudos_count: {
            type: 'integer',
            title: 'Kudos Count',
            default: 0
        },
        featured_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Featured At'
        },
        author_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Author Name'
        },
        author_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Author Url'
        },
        has_kudos: {
            type: 'boolean',
            title: 'Has Kudos',
            default: false
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        links: {
            items: {
                '$ref': '#/components/schemas/GameLinkPublic'
            },
            type: 'array',
            title: 'Links',
            default: []
        },
        tags: {
            items: {
                '$ref': '#/components/schemas/TagPublic'
            },
            type: 'array',
            title: 'Tags',
            default: []
        },
        platforms: {
            items: {
                '$ref': '#/components/schemas/PlatformPublic'
            },
            type: 'array',
            title: 'Platforms',
            default: []
        },
        price_cents: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Cents'
        },
        price_currency: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Currency'
        }
    },
    type: 'object',
    required: ['id', 'slug', 'status', 'submitter_id'],
    title: 'GamePublic'
} as const;

export const GameRejectSchema = {
    properties: {
        rejection_reason: {
            type: 'string',
            maxLength: 1000,
            minLength: 1,
            title: 'Rejection Reason'
        }
    },
    type: 'object',
    required: ['rejection_reason'],
    title: 'GameReject'
} as const;

export const GameSortSchema = {
    type: 'string',
    enum: ['latest', 'title', 'author', 'kudos'],
    title: 'GameSort'
} as const;

export const GameStatusSchema = {
    type: 'string',
    enum: ['pending', 'approved', 'rejected', 'archived'],
    title: 'GameStatus'
} as const;

export const GameSubmitBatchSchema = {
    properties: {
        urls: {
            items: {
                type: 'string'
            },
            type: 'array',
            maxItems: 50,
            minItems: 1,
            title: 'Urls'
        },
        itch_access_token: {
            type: 'string',
            maxLength: 2048,
            minLength: 1,
            title: 'Itch Access Token'
        }
    },
    type: 'object',
    required: ['urls', 'itch_access_token'],
    title: 'GameSubmitBatch'
} as const;

export const GameUpdateSchema = {
    properties: {
        url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        }
    },
    type: 'object',
    title: 'GameUpdate'
} as const;

export const GamesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/GamePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'GamesPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItchAuthCallbackSchema = {
    properties: {
        access_token: {
            type: 'string',
            maxLength: 2048,
            minLength: 1,
            title: 'Access Token'
        },
        state: {
            type: 'string',
            maxLength: 512,
            minLength: 1,
            title: 'State'
        }
    },
    type: 'object',
    required: ['access_token', 'state'],
    title: 'ItchAuthCallback'
} as const;

export const ItchAuthResponseSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        },
        user: {
            '$ref': '#/components/schemas/UserPublic'
        },
        games: {
            items: {
                '$ref': '#/components/schemas/ItchGamePublic'
            },
            type: 'array',
            title: 'Games'
        },
        itch_username: {
            type: 'string',
            title: 'Itch Username'
        }
    },
    type: 'object',
    required: ['access_token', 'user', 'games', 'itch_username'],
    title: 'ItchAuthResponse'
} as const;

export const ItchAuthorizeResponseSchema = {
    properties: {
        authorize_url: {
            type: 'string',
            title: 'Authorize Url'
        },
        state: {
            type: 'string',
            title: 'State'
        }
    },
    type: 'object',
    required: ['authorize_url', 'state'],
    title: 'ItchAuthorizeResponse'
} as const;

export const ItchGamePublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        url: {
            type: 'string',
            title: 'Url'
        },
        cover_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cover Url'
        },
        short_text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Short Text'
        },
        published: {
            type: 'boolean',
            title: 'Published',
            default: true
        },
        classification: {
            type: 'string',
            title: 'Classification',
            default: 'game'
        },
        normalized_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Normalized Url'
        },
        already_indexed: {
            type: 'boolean',
            title: 'Already Indexed',
            default: false
        },
        itch_search_listed: {
            type: 'boolean',
            title: 'Itch Search Listed',
            default: false
        },
        publicly_viewable: {
            type: 'boolean',
            title: 'Publicly Viewable',
            default: true
        }
    },
    type: 'object',
    required: ['id', 'title', 'url'],
    title: 'ItchGamePublic'
} as const;

export const ItchMetadataPreviewSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary'
        },
        cover_image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cover Image Url'
        },
        author_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Author Name'
        },
        author_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Author Url'
        },
        tags: {
            items: {
                '$ref': '#/components/schemas/ItchTagPreview'
            },
            type: 'array',
            title: 'Tags',
            default: []
        },
        normalized_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Normalized Url'
        }
    },
    type: 'object',
    required: ['url'],
    title: 'ItchMetadataPreview'
} as const;

export const ItchTagPreviewSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        itch_url: {
            type: 'string',
            title: 'Itch Url'
        },
        is_genre: {
            type: 'boolean',
            title: 'Is Genre',
            default: false
        }
    },
    type: 'object',
    required: ['name', 'slug', 'itch_url'],
    title: 'ItchTagPreview'
} as const;

export const LinkPlatformSchema = {
    type: 'string',
    enum: ['itch', 'steam', 'website', 'other'],
    title: 'LinkPlatform'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const ModeratorUserPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        itch_username: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Itch Username'
        },
        display_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Display Name'
        },
        is_moderator: {
            type: 'boolean',
            title: 'Is Moderator',
            default: false
        },
        is_owner: {
            type: 'boolean',
            title: 'Is Owner',
            default: false
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id'],
    title: 'ModeratorUserPublic'
} as const;

export const ModeratorUserUpdateSchema = {
    properties: {
        is_moderator: {
            type: 'boolean',
            title: 'Is Moderator'
        }
    },
    type: 'object',
    required: ['is_moderator'],
    title: 'ModeratorUserUpdate'
} as const;

export const ModeratorUsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ModeratorUserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ModeratorUsersPublic'
} as const;

export const NewsletterSubscribeSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'NewsletterSubscribe'
} as const;

export const NewsletterSubscribersPublicSchema = {
    properties: {
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['count'],
    title: 'NewsletterSubscribersPublic'
} as const;

export const OsPlatformSchema = {
    type: 'string',
    enum: ['android', 'windows', 'apple', 'linux', 'web'],
    title: 'OsPlatform'
} as const;

export const PlatformPublicSchema = {
    properties: {
        platform: {
            '$ref': '#/components/schemas/OsPlatform'
        },
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['platform', 'name'],
    title: 'PlatformPublic'
} as const;

export const SubmitBatchItemStatusSchema = {
    type: 'string',
    enum: ['submitted', 'duplicate', 'not_owned', 'still_listed', 'not_public', 'error'],
    title: 'SubmitBatchItemStatus'
} as const;

export const SubmitBatchResponseSchema = {
    properties: {
        results: {
            items: {
                '$ref': '#/components/schemas/SubmitBatchResultItem'
            },
            type: 'array',
            title: 'Results'
        },
        submitted_count: {
            type: 'integer',
            title: 'Submitted Count'
        },
        skipped_count: {
            type: 'integer',
            title: 'Skipped Count'
        }
    },
    type: 'object',
    required: ['results', 'submitted_count', 'skipped_count'],
    title: 'SubmitBatchResponse'
} as const;

export const SubmitBatchResultItemSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url'
        },
        status: {
            '$ref': '#/components/schemas/SubmitBatchItemStatus'
        },
        game: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/GamePublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        detail: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Detail'
        }
    },
    type: 'object',
    required: ['url', 'status'],
    title: 'SubmitBatchResultItem'
} as const;

export const TagPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        itch_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Itch Url'
        },
        is_genre: {
            type: 'boolean',
            title: 'Is Genre',
            default: false
        }
    },
    type: 'object',
    required: ['id', 'name', 'slug'],
    title: 'TagPublic'
} as const;

export const TagsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TagPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'TagsPublic'
} as const;

export const UserProfileLinkSchema = {
    properties: {
        label: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Label'
        },
        url: {
            type: 'string',
            maxLength: 2048,
            minLength: 1,
            title: 'Url'
        },
        managed_by_itch: {
            type: 'boolean',
            title: 'Managed By Itch',
            default: false
        }
    },
    type: 'object',
    required: ['label', 'url'],
    title: 'UserProfileLink'
} as const;

export const UserProfileLinksUpdateSchema = {
    properties: {
        links: {
            items: {
                '$ref': '#/components/schemas/UserProfileLink'
            },
            type: 'array',
            maxItems: 7,
            title: 'Links'
        }
    },
    type: 'object',
    title: 'UserProfileLinksUpdate'
} as const;

export const UserPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        itch_username: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Itch Username'
        },
        display_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Display Name'
        },
        is_owner: {
            type: 'boolean',
            title: 'Is Owner',
            default: false
        },
        is_moderator: {
            type: 'boolean',
            title: 'Is Moderator',
            default: false
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        profile_links: {
            items: {
                '$ref': '#/components/schemas/UserProfileLink'
            },
            type: 'array',
            title: 'Profile Links'
        }
    },
    type: 'object',
    required: ['id'],
    title: 'UserPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;