// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { AdminReadAdminGamesData, AdminReadAdminGamesResponse, AdminCreateAdminGameData, AdminCreateAdminGameResponse, AdminFeatureAdminGameData, AdminFeatureAdminGameResponse, AdminUnfeatureAdminGameData, AdminUnfeatureAdminGameResponse, AdminDeleteAdminGameData, AdminDeleteAdminGameResponse, AdminReadAdminUsersData, AdminReadAdminUsersResponse, AdminUpdateAdminUserData, AdminUpdateAdminUserResponse, AdminReadNewsletterSubscribersResponse, AdminDownloadNewsletterSubscribersCsvResponse, GamesReadGamesData, GamesReadGamesResponse, GamesCreateGameData, GamesCreateGameResponse, GamesReadFeaturedGamesData, GamesReadFeaturedGamesResponse, GamesReadMyGamesData, GamesReadMyGamesResponse, GamesPrefillItchMetadataData, GamesPrefillItchMetadataResponse, GamesCheckDuplicateData, GamesCheckDuplicateResponse, GamesSubmitGamesBatchData, GamesSubmitGamesBatchResponse, GamesReadGameData, GamesReadGameResponse, GamesAddKudosData, GamesAddKudosResponse, GamesUpdateGameData, GamesUpdateGameResponse, ItchAuthItchAuthorizeResponse, ItchAuthItchCallbackData, ItchAuthItchCallbackResponse, ModerationReadModerationQueueData, ModerationReadModerationQueueResponse, ModerationApproveGameData, ModerationApproveGameResponse, ModerationFeatureGameData, ModerationFeatureGameResponse, ModerationRejectGameData, ModerationRejectGameResponse, ModerationCheckDuplicatesData, ModerationCheckDuplicatesResponse, NewsletterSubscribeToNewsletterData, NewsletterSubscribeToNewsletterResponse, TagsReadTagsResponse, TagsReadGamesByTagData, TagsReadGamesByTagResponse, UsersReadUserMeResponse, UsersUpdateUserProfileLinksData, UsersUpdateUserProfileLinksResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class AdminService {
    /**
     * Read Admin Games
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @param data.search
     * @returns AdminGamesPublic Successful Response
     * @throws ApiError
     */
    public static readAdminGames(data: AdminReadAdminGamesData = {}): CancelablePromise<AdminReadAdminGamesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/admin/games',
            query: {
                skip: data.skip,
                limit: data.limit,
                search: data.search
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Admin Game
     * @param data The data for the request.
     * @param data.requestBody
     * @returns AdminGamePublic Successful Response
     * @throws ApiError
     */
    public static createAdminGame(data: AdminCreateAdminGameData): CancelablePromise<AdminCreateAdminGameResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/admin/games',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Feature Admin Game
     * @param data The data for the request.
     * @param data.id
     * @returns AdminGamePublic Successful Response
     * @throws ApiError
     */
    public static featureAdminGame(data: AdminFeatureAdminGameData): CancelablePromise<AdminFeatureAdminGameResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/admin/games/{id}/feature',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Unfeature Admin Game
     * @param data The data for the request.
     * @param data.id
     * @returns AdminGamePublic Successful Response
     * @throws ApiError
     */
    public static unfeatureAdminGame(data: AdminUnfeatureAdminGameData): CancelablePromise<AdminUnfeatureAdminGameResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/admin/games/{id}/unfeature',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Admin Game
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteAdminGame(data: AdminDeleteAdminGameData): CancelablePromise<AdminDeleteAdminGameResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/admin/games/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Admin Users
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ModeratorUsersPublic Successful Response
     * @throws ApiError
     */
    public static readAdminUsers(data: AdminReadAdminUsersData = {}): CancelablePromise<AdminReadAdminUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/admin/users',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Admin User
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns ModeratorUserPublic Successful Response
     * @throws ApiError
     */
    public static updateAdminUser(data: AdminUpdateAdminUserData): CancelablePromise<AdminUpdateAdminUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/admin/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Newsletter Subscribers
     * @returns NewsletterSubscribersPublic Successful Response
     * @throws ApiError
     */
    public static readNewsletterSubscribers(): CancelablePromise<AdminReadNewsletterSubscribersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/admin/newsletter/subscribers'
        });
    }
    
    /**
     * Download Newsletter Subscribers Csv
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static downloadNewsletterSubscribersCsv(): CancelablePromise<AdminDownloadNewsletterSubscribersCsvResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/admin/newsletter/subscribers.csv'
        });
    }
}

export class GamesService {
    /**
     * Read Games
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @param data.search
     * @param data.sort
     * @param data.tagSlugs
     * @param data.platforms
     * @param data.xKudosVisitorId
     * @returns GamesPublic Successful Response
     * @throws ApiError
     */
    public static readGames(data: GamesReadGamesData = {}): CancelablePromise<GamesReadGamesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/games/',
            headers: {
                'X-Kudos-Visitor-Id': data.xKudosVisitorId
            },
            query: {
                skip: data.skip,
                limit: data.limit,
                search: data.search,
                sort: data.sort,
                tag_slugs: data.tagSlugs,
                platforms: data.platforms
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Game
     * @param data The data for the request.
     * @param data.requestBody
     * @returns GamePublic Successful Response
     * @throws ApiError
     */
    public static createGame(data: GamesCreateGameData): CancelablePromise<GamesCreateGameResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/games/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Featured Games
     * @param data The data for the request.
     * @param data.limit
     * @param data.xKudosVisitorId
     * @returns GamesPublic Successful Response
     * @throws ApiError
     */
    public static readFeaturedGames(data: GamesReadFeaturedGamesData = {}): CancelablePromise<GamesReadFeaturedGamesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/games/featured',
            headers: {
                'X-Kudos-Visitor-Id': data.xKudosVisitorId
            },
            query: {
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read My Games
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns GamesPublic Successful Response
     * @throws ApiError
     */
    public static readMyGames(data: GamesReadMyGamesData = {}): CancelablePromise<GamesReadMyGamesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/games/me',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Prefill Itch Metadata
     * @param data The data for the request.
     * @param data.url
     * @returns ItchMetadataPreview Successful Response
     * @throws ApiError
     */
    public static prefillItchMetadata(data: GamesPrefillItchMetadataData): CancelablePromise<GamesPrefillItchMetadataResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/games/prefill-itch',
            query: {
                url: data.url
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Check Duplicate
     * @param data The data for the request.
     * @param data.url
     * @param data.title
     * @returns DuplicateCheckResult Successful Response
     * @throws ApiError
     */
    public static checkDuplicate(data: GamesCheckDuplicateData): CancelablePromise<GamesCheckDuplicateResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/games/check-duplicate',
            query: {
                url: data.url,
                title: data.title
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Submit Games Batch
     * @param data The data for the request.
     * @param data.requestBody
     * @returns SubmitBatchResponse Successful Response
     * @throws ApiError
     */
    public static submitGamesBatch(data: GamesSubmitGamesBatchData): CancelablePromise<GamesSubmitGamesBatchResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/games/submit-batch',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Game
     * @param data The data for the request.
     * @param data.slug
     * @param data.xKudosVisitorId
     * @returns GamePublic Successful Response
     * @throws ApiError
     */
    public static readGame(data: GamesReadGameData): CancelablePromise<GamesReadGameResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/games/{slug}',
            path: {
                slug: data.slug
            },
            headers: {
                'X-Kudos-Visitor-Id': data.xKudosVisitorId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Add Kudos
     * @param data The data for the request.
     * @param data.slug
     * @param data.xKudosVisitorId
     * @returns GamePublic Successful Response
     * @throws ApiError
     */
    public static addKudos(data: GamesAddKudosData): CancelablePromise<GamesAddKudosResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/games/{slug}/kudos',
            path: {
                slug: data.slug
            },
            headers: {
                'X-Kudos-Visitor-Id': data.xKudosVisitorId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Game
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns GamePublic Successful Response
     * @throws ApiError
     */
    public static updateGame(data: GamesUpdateGameData): CancelablePromise<GamesUpdateGameResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/games/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ItchAuthService {
    /**
     * Itch Authorize
     * @returns ItchAuthorizeResponse Successful Response
     * @throws ApiError
     */
    public static itchAuthorize(): CancelablePromise<ItchAuthItchAuthorizeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/auth/itch/authorize'
        });
    }
    
    /**
     * Itch Callback
     * @param data The data for the request.
     * @param data.requestBody
     * @param data.xKudosVisitorId
     * @returns ItchAuthResponse Successful Response
     * @throws ApiError
     */
    public static itchCallback(data: ItchAuthItchCallbackData): CancelablePromise<ItchAuthItchCallbackResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/auth/itch/callback',
            headers: {
                'X-Kudos-Visitor-Id': data.xKudosVisitorId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ModerationService {
    /**
     * Read Moderation Queue
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns GamesPublic Successful Response
     * @throws ApiError
     */
    public static readModerationQueue(data: ModerationReadModerationQueueData = {}): CancelablePromise<ModerationReadModerationQueueResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/moderation/queue',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Approve Game
     * @param data The data for the request.
     * @param data.id
     * @returns GamePublic Successful Response
     * @throws ApiError
     */
    public static approveGame(data: ModerationApproveGameData): CancelablePromise<ModerationApproveGameResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/moderation/games/{id}/approve',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Feature Game
     * @param data The data for the request.
     * @param data.id
     * @returns GamePublic Successful Response
     * @throws ApiError
     */
    public static featureGame(data: ModerationFeatureGameData): CancelablePromise<ModerationFeatureGameResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/moderation/games/{id}/feature',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reject Game
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns GamePublic Successful Response
     * @throws ApiError
     */
    public static rejectGame(data: ModerationRejectGameData): CancelablePromise<ModerationRejectGameResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/moderation/games/{id}/reject',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Check Duplicates
     * @param data The data for the request.
     * @param data.url
     * @returns DuplicateCheckResult Successful Response
     * @throws ApiError
     */
    public static checkDuplicates(data: ModerationCheckDuplicatesData): CancelablePromise<ModerationCheckDuplicatesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/moderation/duplicates',
            query: {
                url: data.url
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class NewsletterService {
    /**
     * Subscribe To Newsletter
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static subscribeToNewsletter(data: NewsletterSubscribeToNewsletterData): CancelablePromise<NewsletterSubscribeToNewsletterResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/newsletter/subscribe',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class TagsService {
    /**
     * Read Tags
     * @returns TagsPublic Successful Response
     * @throws ApiError
     */
    public static readTags(): CancelablePromise<TagsReadTagsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/tags/'
        });
    }
    
    /**
     * Read Games By Tag
     * @param data The data for the request.
     * @param data.slug
     * @param data.skip
     * @param data.limit
     * @param data.search
     * @returns GamesPublic Successful Response
     * @throws ApiError
     */
    public static readGamesByTag(data: TagsReadGamesByTagData): CancelablePromise<TagsReadGamesByTagResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/tags/{slug}/games',
            path: {
                slug: data.slug
            },
            query: {
                skip: data.skip,
                limit: data.limit,
                search: data.search
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Profile Links
     * Update custom profile links. The itch.io profile link is always included
     * automatically and cannot be removed.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserProfileLinks(data: UsersUpdateUserProfileLinksData): CancelablePromise<UsersUpdateUserProfileLinksResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/profile-links',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}