// This file is auto-generated by @hey-api/openapi-ts

export type AdminGamePublic = {
    id: string;
    itch_url: string;
    title?: (string | null);
    status: GameStatus;
    featured_at?: (string | null);
    created_at?: (string | null);
};

export type AdminGamesPublic = {
    data: Array<AdminGamePublic>;
    count: number;
};

export type DuplicateCheckResult = {
    url_exists?: boolean;
    existing_game_slug?: (string | null);
    similar_titles?: Array<(string)>;
};

export type GameCreate = {
    url: string;
};

export type GameLinkPublic = {
    id: string;
    url: string;
    platform?: LinkPlatform;
    is_primary?: boolean;
    normalized_url: string;
};

export type GamePublic = {
    id: string;
    slug: string;
    title?: (string | null);
    summary?: (string | null);
    description?: (string | null);
    cover_image_url?: (string | null);
    status: GameStatus;
    submitter_id: string;
    submitter_itch_username?: (string | null);
    reviewed_at?: (string | null);
    rejection_reason?: (string | null);
    duplicate_title_warning?: boolean;
    kudos_count?: number;
    featured_at?: (string | null);
    author_name?: (string | null);
    author_url?: (string | null);
    has_kudos?: boolean;
    created_at?: (string | null);
    updated_at?: (string | null);
    links?: Array<GameLinkPublic>;
    tags?: Array<TagPublic>;
    platforms?: Array<PlatformPublic>;
    price_cents?: (number | null);
    price_currency?: (string | null);
};

export type GameReject = {
    rejection_reason: string;
};

export type GameSort = 'latest' | 'title' | 'author' | 'kudos';

export type GamesPublic = {
    data: Array<GamePublic>;
    count: number;
};

export type GameStatus = 'pending' | 'approved' | 'rejected' | 'archived';

export type GameSubmitBatch = {
    urls: Array<(string)>;
    itch_access_token: string;
};

export type GameUpdate = {
    url?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItchAuthCallback = {
    access_token: string;
    state: string;
};

export type ItchAuthorizeResponse = {
    authorize_url: string;
    state: string;
};

export type ItchAuthResponse = {
    access_token: string;
    token_type?: string;
    user: UserPublic;
    games: Array<ItchGamePublic>;
    itch_username: string;
};

export type ItchGamePublic = {
    id: number;
    title: string;
    url: string;
    cover_url?: (string | null);
    short_text?: (string | null);
    published?: boolean;
    classification?: string;
    normalized_url?: (string | null);
    already_indexed?: boolean;
    itch_search_listed?: boolean;
    publicly_viewable?: boolean;
};

export type ItchMetadataPreview = {
    url: string;
    title?: (string | null);
    summary?: (string | null);
    cover_image_url?: (string | null);
    author_name?: (string | null);
    author_url?: (string | null);
    tags?: Array<ItchTagPreview>;
    normalized_url?: (string | null);
};

export type ItchTagPreview = {
    name: string;
    slug: string;
    itch_url: string;
    is_genre?: boolean;
};

export type LinkPlatform = 'itch' | 'steam' | 'website' | 'other';

export type Message = {
    message: string;
};

export type ModeratorUserPublic = {
    id: string;
    itch_username?: (string | null);
    display_name?: (string | null);
    is_moderator?: boolean;
    is_owner?: boolean;
    created_at?: (string | null);
};

export type ModeratorUsersPublic = {
    data: Array<ModeratorUserPublic>;
    count: number;
};

export type ModeratorUserUpdate = {
    is_moderator: boolean;
};

export type NewsletterSubscribe = {
    email: string;
};

export type NewsletterSubscribersPublic = {
    count: number;
};

export type OsPlatform = 'android' | 'windows' | 'apple' | 'linux' | 'web';

export type PlatformPublic = {
    platform: OsPlatform;
    name: string;
};

export type SubmitBatchItemStatus = 'submitted' | 'duplicate' | 'not_owned' | 'still_listed' | 'not_public' | 'error';

export type SubmitBatchResponse = {
    results: Array<SubmitBatchResultItem>;
    submitted_count: number;
    skipped_count: number;
};

export type SubmitBatchResultItem = {
    url: string;
    status: SubmitBatchItemStatus;
    game?: (GamePublic | null);
    detail?: (string | null);
};

export type TagPublic = {
    id: string;
    name: string;
    slug: string;
    itch_url?: (string | null);
    is_genre?: boolean;
};

export type TagsPublic = {
    data: Array<TagPublic>;
    count: number;
};

export type UserProfileLink = {
    label: string;
    url: string;
    managed_by_itch?: boolean;
};

export type UserProfileLinksUpdate = {
    links?: Array<UserProfileLink>;
};

export type UserPublic = {
    id: string;
    itch_username?: (string | null);
    display_name?: (string | null);
    is_owner?: boolean;
    is_moderator?: boolean;
    created_at?: (string | null);
    profile_links?: Array<UserProfileLink>;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AdminReadAdminGamesData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type AdminReadAdminGamesResponse = (AdminGamesPublic);

export type AdminCreateAdminGameData = {
    requestBody: GameCreate;
};

export type AdminCreateAdminGameResponse = (AdminGamePublic);

export type AdminFeatureAdminGameData = {
    id: string;
};

export type AdminFeatureAdminGameResponse = (AdminGamePublic);

export type AdminUnfeatureAdminGameData = {
    id: string;
};

export type AdminUnfeatureAdminGameResponse = (AdminGamePublic);

export type AdminDeleteAdminGameData = {
    id: string;
};

export type AdminDeleteAdminGameResponse = (Message);

export type AdminReadAdminUsersData = {
    limit?: number;
    skip?: number;
};

export type AdminReadAdminUsersResponse = (ModeratorUsersPublic);

export type AdminUpdateAdminUserData = {
    requestBody: ModeratorUserUpdate;
    userId: string;
};

export type AdminUpdateAdminUserResponse = (ModeratorUserPublic);

export type AdminReadNewsletterSubscribersResponse = (NewsletterSubscribersPublic);

export type AdminDownloadNewsletterSubscribersCsvResponse = (unknown);

export type GamesReadGamesData = {
    limit?: number;
    platforms?: Array<OsPlatform>;
    search?: (string | null);
    skip?: number;
    sort?: GameSort;
    tagSlugs?: Array<(string)>;
    xKudosVisitorId?: (string | null);
};

export type GamesReadGamesResponse = (GamesPublic);

export type GamesCreateGameData = {
    requestBody: GameCreate;
};

export type GamesCreateGameResponse = (GamePublic);

export type GamesReadFeaturedGamesData = {
    limit?: number;
    xKudosVisitorId?: (string | null);
};

export type GamesReadFeaturedGamesResponse = (GamesPublic);

export type GamesReadMyGamesData = {
    limit?: number;
    skip?: number;
};

export type GamesReadMyGamesResponse = (GamesPublic);

export type GamesPrefillItchMetadataData = {
    url: string;
};

export type GamesPrefillItchMetadataResponse = (ItchMetadataPreview);

export type GamesCheckDuplicateData = {
    title?: (string | null);
    url: string;
};

export type GamesCheckDuplicateResponse = (DuplicateCheckResult);

export type GamesSubmitGamesBatchData = {
    requestBody: GameSubmitBatch;
};

export type GamesSubmitGamesBatchResponse = (SubmitBatchResponse);

export type GamesReadGameData = {
    slug: string;
    xKudosVisitorId?: (string | null);
};

export type GamesReadGameResponse = (GamePublic);

export type GamesAddKudosData = {
    slug: string;
    xKudosVisitorId?: (string | null);
};

export type GamesAddKudosResponse = (GamePublic);

export type GamesUpdateGameData = {
    id: string;
    requestBody: GameUpdate;
};

export type GamesUpdateGameResponse = (GamePublic);

export type ItchAuthItchAuthorizeResponse = (ItchAuthorizeResponse);

export type ItchAuthItchCallbackData = {
    requestBody: ItchAuthCallback;
    xKudosVisitorId?: (string | null);
};

export type ItchAuthItchCallbackResponse = (ItchAuthResponse);

export type ModerationReadModerationQueueData = {
    limit?: number;
    skip?: number;
};

export type ModerationReadModerationQueueResponse = (GamesPublic);

export type ModerationApproveGameData = {
    id: string;
};

export type ModerationApproveGameResponse = (GamePublic);

export type ModerationFeatureGameData = {
    id: string;
};

export type ModerationFeatureGameResponse = (GamePublic);

export type ModerationRejectGameData = {
    id: string;
    requestBody: GameReject;
};

export type ModerationRejectGameResponse = (GamePublic);

export type ModerationCheckDuplicatesData = {
    url: string;
};

export type ModerationCheckDuplicatesResponse = (DuplicateCheckResult);

export type NewsletterSubscribeToNewsletterData = {
    requestBody: NewsletterSubscribe;
};

export type NewsletterSubscribeToNewsletterResponse = (Message);

export type TagsReadTagsResponse = (TagsPublic);

export type TagsReadGamesByTagData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
    slug: string;
};

export type TagsReadGamesByTagResponse = (GamesPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersUpdateUserProfileLinksData = {
    requestBody: UserProfileLinksUpdate;
};

export type UsersUpdateUserProfileLinksResponse = (UserPublic);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);