/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSubmitRouteImport } from './routes/_public/submit'
import { Route as PublicAdminRouteImport } from './routes/_public/admin'
import { Route as PublicSubmitCallbackRouteImport } from './routes/_public/submit.callback'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSubmitRoute = PublicSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAdminRoute = PublicAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSubmitCallbackRoute = PublicSubmitCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => PublicSubmitRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof PublicAdminRoute
  '/submit': typeof PublicSubmitRouteWithChildren
  '/submit/callback': typeof PublicSubmitCallbackRoute
}
export interface FileRoutesByTo {
  '/admin': typeof PublicAdminRoute
  '/submit': typeof PublicSubmitRouteWithChildren
  '/': typeof PublicIndexRoute
  '/submit/callback': typeof PublicSubmitCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_public/admin': typeof PublicAdminRoute
  '/_public/submit': typeof PublicSubmitRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_public/submit/callback': typeof PublicSubmitCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/submit' | '/submit/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/admin' | '/submit' | '/' | '/submit/callback'
  id:
    | '__root__'
    | '/_public'
    | '/_public/admin'
    | '/_public/submit'
    | '/_public/'
    | '/_public/submit/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/submit': {
      id: '/_public/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof PublicSubmitRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/admin': {
      id: '/_public/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof PublicAdminRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/submit/callback': {
      id: '/_public/submit/callback'
      path: '/callback'
      fullPath: '/submit/callback'
      preLoaderRoute: typeof PublicSubmitCallbackRouteImport
      parentRoute: typeof PublicSubmitRoute
    }
  }
}

interface PublicSubmitRouteChildren {
  PublicSubmitCallbackRoute: typeof PublicSubmitCallbackRoute
}

const PublicSubmitRouteChildren: PublicSubmitRouteChildren = {
  PublicSubmitCallbackRoute: PublicSubmitCallbackRoute,
}

const PublicSubmitRouteWithChildren = PublicSubmitRoute._addFileChildren(
  PublicSubmitRouteChildren,
)

interface PublicRouteChildren {
  PublicAdminRoute: typeof PublicAdminRoute
  PublicSubmitRoute: typeof PublicSubmitRouteWithChildren
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAdminRoute: PublicAdminRoute,
  PublicSubmitRoute: PublicSubmitRouteWithChildren,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
